const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { test, after, beforeEach } = require('node:test')
const { buildSync } = require('esbuild')

process.env.TZ = 'Europe/Paris'
const root = path.resolve(__dirname, '..')
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'doneline-search-planning-'))
process.env.DONELINE_DIR = path.join(temporary, 'data')
process.env.DONELINE_DB = ':memory:'
const compiled = path.join(temporary, 'core.cjs')
buildSync({ stdin: { contents: `export * from './core/search'; export * from './core/db'; export * from './core/todos'; export * from './core/events'; export * from './core/goals'; export * from './core/notes'; export * from './core/people'; export * from './core/recurrence'; export * from './src/renderer/src/lib/taskPlanning';`, loader: 'ts', resolveDir: root }, bundle: true, platform: 'node', format: 'cjs', external: ['libsql'], banner: { js: `module.paths.unshift(${JSON.stringify(path.join(root, 'node_modules'))});` }, outfile: compiled, logLevel: 'silent' })
const core = require(compiled)
const db = core.getDb()
const [alice, bob] = core.listPeople()
const local = (day, time = '09:00') => new Date(`${day}T${time}:00`).toISOString()
beforeEach(() => {
  for (const table of ['todo_completions', 'reactions', 'todos', 'events', 'goals', 'daily_notes']) db.prepare(`DELETE FROM ${table}`).run()
})
after(() => {
  core.closeDb()
  assert.equal(path.dirname(temporary), path.resolve(os.tmpdir()))
  assert.ok(path.basename(temporary).startsWith('doneline-search-planning-'))
  fs.rmSync(temporary, { recursive: true, force: true })
})

test('planning groups local midnight, future dates, undated and per-person shared completion', () => {
  const today = core.createTodo({ title: 'Midnight', due_at: local('2026-10-10', '00:15') })
  const overdue = core.createTodo({ title: 'Overdue', due_at: local('2026-10-09', '23:55') })
  const upcoming = core.createTodo({ title: 'Future', due_at: local('2026-10-11') })
  const undated = core.createTodo({ title: 'Undated' })
  const goal = core.createGoal({ title: 'Shared', person_id: alice.id, shared: true })
  const shared = core.createTodo({ title: 'Done by me', goal_id: goal.id })
  db.prepare('INSERT INTO todo_completions(todo_id,person_id) VALUES (?,?)').run(shared.id, alice.id)
  core.createTodo({ title: 'Rule', recurrence: JSON.stringify({ freq: 'daily', startDate: '2026-10-10' }) })
  const archived = core.createTodo({ title: 'Archived' })
  db.prepare('UPDATE todos SET archived=1 WHERE id=?').run(archived.id)
  const rows = core.listPlannedTodos('2026-10-10')
  assert.equal(rows.length, 5)
  const result = core.groupTasks(rows, '2026-10-10', alice.id)
  assert.deepEqual(Object.fromEntries(Object.entries(result.groups).map(([key, rows]) => [key, rows.map(row => row.id)])), { today: [today.id], overdue: [overdue.id], upcoming: [upcoming.id], undated: [undated.id] })
  assert.equal(result.remaining, 4)
  assert.deepEqual(result.finished.map(row => row.id), [shared.id])
  assert.equal(core.groupTasks(rows, '2026-10-10', bob.id).remaining, 5)
})

test('quick scheduling preserves local time across DST, accepts no date, rejects nonexistent clock time', () => {
  const task = core.createTodo({ title: 'DST time', due_at: local('2026-03-28', '02:30') })
  assert.throws(() => core.rescheduledDue(task, '2026-03-29'), /does not exist/)
  assert.equal(core.rescheduledDue(task, '2026-03-30'), local('2026-03-30', '02:30'))
  assert.equal(core.rescheduledDue(task, null), null)
  assert.equal(core.tomorrowDay('2026-03-29'), '2026-03-30')
  assert.equal(core.tomorrowDay('2026-12-31'), '2027-01-01')
  assert.equal(core.rescheduledDue({ ...task, due_at: null }, '2026-10-11'), local('2026-10-11'))
})

test('global search matches accents/details literally, includes finished history, excludes templates and filters private profiles', () => {
  const privateGoal = core.createGoal({ title: 'Café private goal', person_id: bob.id })
  const sharedGoal = core.createGoal({ title: 'Café shared goal', person_id: bob.id, shared: true })
  const task = core.createTodo({ title: 'Read chapter', notes: 'Café project details', goal_id: sharedGoal.id, person_id: bob.id })
  const archived = core.createTodo({ title: 'Café completed', person_id: alice.id })
  db.prepare('UPDATE todos SET archived=1,completed_at=? WHERE id=?').run(local('2026-10-09'), archived.id)
  core.createTodo({ title: 'Café repeat rule', recurrence: JSON.stringify({ freq: 'daily' }) })
  const event = core.createEvent({ title: 'Catch up', location: 'Café meeting room', starts_at: local('2026-10-12'), ends_at: local('2026-10-12', '10:00'), person_id: bob.id, shared: true })
  core.createEvent({ title: 'Café private event', starts_at: local('2026-10-13'), ends_at: local('2026-10-13', '10:00'), person_id: bob.id })
  core.setDailyNote('2026-10-09', 'Café thoughts from yesterday.', alice.id)
  core.setDailyNote('2026-10-08', 'Café private note.', bob.id)
  const result = core.searchWorkspace({ query: 'CAFE', personId: alice.id })
  assert.deepEqual(new Set(result.todos.map(row => row.id)), new Set([task.id, archived.id]))
  assert.deepEqual(result.events.map(row => row.id), [event.id])
  assert.deepEqual(result.goals.map(row => row.id), [sharedGoal.id])
  assert.deepEqual(result.notes.map(row => row.day), ['2026-10-09'])
  assert.equal(core.searchWorkspace({ query: 'cafe', personId: 'all' }).goals.length, 2)
  assert.ok(core.searchWorkspace({ query: 'cafe', personId: bob.id }).goals.some(row => row.id === privateGoal.id))
  const literal = core.createTodo({ title: '100%_literal' })
  assert.deepEqual(core.searchWorkspace({ query: '%_' }).todos.map(row => row.id), [literal.id])
  assert.equal(core.searchWorkspace({ query: 'cafe project' }).todos[0].id, task.id)
})

test('search reads do not generate recurring rows, rank titles first, and validate query/limits', () => {
  const bodyMatch = core.createTodo({ title: 'A body match', notes: 'needle' })
  const titleMatch = core.createTodo({ title: 'Needle in title' })
  core.createTodo({ title: 'Needle rule', recurrence: JSON.stringify({ freq: 'daily' }) })
  const before = db.prepare('SELECT COUNT(*) AS n FROM todos').get().n
  assert.deepEqual(core.searchWorkspace({ query: 'needle', limit: 1 }).todos.map(row => row.id), [titleMatch.id])
  assert.ok(core.searchWorkspace({ query: 'needle' }).todos.some(row => row.id === bodyMatch.id))
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM todos').get().n, before)
  assert.deepEqual(core.searchWorkspace({ query: '   ' }), { todos: [], events: [], goals: [], notes: [] })
  assert.throws(() => core.searchWorkspace({ query: 'x', limit: 51 }), /Search limit/)
  assert.throws(() => core.searchWorkspace({ query: 'x'.repeat(201) }), /200 characters/)
})
