const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { test, beforeEach, after } = require('node:test')
const { buildSync } = require('esbuild')

process.env.TZ = 'Europe/Paris'
const root = path.resolve(__dirname, '..')
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'doneline-trash-backups-'))
process.env.DONELINE_DIR = path.join(directory, 'data')
process.env.DONELINE_DB = ':memory:'
const compiled = path.join(directory, 'core.cjs')
buildSync({ entryPoints: [path.join(root, 'core/index.ts')], bundle: true, platform: 'node', format: 'cjs',
  external: ['libsql'], banner: { js: `module.paths.unshift(${JSON.stringify(path.join(root, 'node_modules'))});` }, outfile: compiled, logLevel: 'silent' })
const core = require(compiled)
const syncCompiled = path.join(directory, 'sync.cjs')
buildSync({ entryPoints: [path.join(root, 'core/offlineSync.ts')], bundle: true, platform: 'node', format: 'cjs',
  outfile: syncCompiled, logLevel: 'silent' })
const sync = require(syncCompiled)
const db = core.getDb()
const [me, friend] = core.listPeople()
const iso = (day, time = '09:00') => new Date(`${day}T${time}:00`).toISOString()
const task = (title, extra = {}) => core.createTodo({ title, person_id: me.id, ...extra })
const event = (title, extra = {}) => core.createEvent({ title, starts_at: iso('2026-10-08'), ends_at: iso('2026-10-08', '10:00'), person_id: me.id, ...extra })
function backupFile(id) {
  const base = path.join(process.env.DONELINE_DIR, 'backups')
  for (const folder of fs.readdirSync(base)) {
    const file = path.join(base, folder, `${id}.doneline-backup.json`)
    if (fs.existsSync(file)) return file
  }
  throw new Error('Backup fixture file missing')
}

beforeEach(() => {
  for (const table of ['todo_completions', 'reactions', 'todos', 'goals', 'events', 'trash_items', 'calendar_tombstones', 'calendar_resources', 'calendar_resource_changes', 'recurrence_exclusions', 'daily_notes', 'settings']) db.prepare(`DELETE FROM ${table}`).run()
})
after(async () => {
  core.closeDb()
  // libSQL releases file handles on its worker thread after close returns.
  await new Promise(resolve => setTimeout(resolve, 50))
  assert.equal(path.dirname(path.resolve(directory)), path.resolve(os.tmpdir()))
  assert.ok(path.basename(directory).startsWith('doneline-trash-backups-'))
  fs.rmSync(directory, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 })
})

test('Trash restores exact shared completion and reactions, without overwriting a reused identity', () => {
  const goal = core.createGoal({ title: 'Shared project', person_id: me.id, shared: true })
  const row = task('Finished shared task', { goal_id: goal.id, due_at: iso('2026-10-08') })
  core.setTodoDone(row.id, true, me.id)
  core.setTodoDone(row.id, true, friend.id)
  core.toggleReaction(row.id, friend.id, '🌟')
  const before = core.getTodo(row.id)
  const removed = core.deleteTodo(row.id)
  assert.equal(core.getTodo(row.id), undefined)
  assert.equal(core.listTrash()[0].item_id, row.id)
  core.restoreTrash(removed)
  assert.equal(core.getTodo(row.id).completed_at, before.completed_at)
  assert.equal(core.getTodo(row.id).done_by, before.done_by)
  assert.equal(core.listReactionsForTodo(row.id)[0].emoji, '🌟')
  assert.equal(core.listTrash().length, 0)
  assert.throws(() => core.restoreTrash(removed), /no longer/)

  const again = core.deleteTodo(row.id)
  db.prepare('INSERT INTO todos(id,title,person_id) VALUES (?,?,?)').run(row.id, 'Newer identity occupant', me.id)
  assert.throws(() => core.restoreTrash(again), /already exists/)
  assert.equal(core.getTodo(row.id).title, 'Newer identity occupant')
  assert.equal(core.listTrash().length, 1)
})

test('restoring separate removed occurrences undoes their own exclusions and preserves the others', () => {
  const rule = task('Thursday prep', { due_at: iso('2026-10-01'), recurrence: JSON.stringify({ freq: 'weekly', days: [4], startDate: '2026-10-01', endDate: '2026-10-22' }) })
  core.ensureTodoInstancesForRange('2026-10-01', '2026-10-22')
  const rows = db.prepare('SELECT * FROM todos WHERE recur_parent = ? ORDER BY due_at').all(rule.id)
  const first = core.deleteTodo(rows[1].id)
  const second = core.deleteTodo(rows[2].id)
  core.ensureTodoInstancesForRange('2026-10-01', '2026-10-22')
  assert.equal(core.getTodo(rows[1].id), undefined)
  core.restoreTrash(first)
  assert.equal(core.getTodo(rows[1].id).recur_parent, rule.id)
  assert.deepEqual(JSON.parse(core.getTodo(rule.id).recurrence).excludedDates, ['2026-10-15'])
  core.restoreTrash(second)
  assert.equal(core.getTodo(rows[2].id).recur_parent, rule.id)
  assert.deepEqual(JSON.parse(core.getTodo(rule.id).recurrence).excludedDates ?? [], [])
  assert.equal(db.prepare("SELECT excluded FROM recurrence_exclusions WHERE kind = 'task' AND parent_id = ? AND day = ?").get(rule.id,'2026-10-08').excluded,0)
  // Even if another device's stale JSON reintroduces an old exclusion, keyed Undo wins.
  const stale = JSON.parse(core.getTodo(rule.id).recurrence)
  stale.excludedDates = ['2026-10-08']
  db.prepare('UPDATE todos SET recurrence = ? WHERE id = ?').run(JSON.stringify(stale),rule.id)
  const again = core.deleteTodo(rows[1].id)
  core.restoreTrash(again)
  assert.equal(db.prepare("SELECT excluded FROM recurrence_exclusions WHERE kind = 'task' AND parent_id = ? AND day = ?").get(rule.id,'2026-10-08').excluded,0)
  assert.deepEqual(JSON.parse(core.getTodo(rule.id).recurrence).excludedDates ?? [], [])
  core.ensureTodoInstancesForRange('2026-10-01', '2026-10-22')
  assert.equal(db.prepare('SELECT COUNT(*) n FROM todos WHERE recur_parent = ?').get(rule.id).n, 4)
})

test('restoring a whole repeat rule retains completed and partial shared history without overwriting edits', () => {
  const goal = core.createGoal({ title: 'Shared recurring goal', person_id: me.id, shared: true })
  const rule = task('Shared weekly review', { goal_id: goal.id, due_at: iso('2026-10-01'), recurrence: JSON.stringify({ freq: 'weekly', days: [4], startDate: '2026-10-01', endDate: '2026-10-15' }) })
  core.ensureTodoInstancesForRange('2026-10-01', '2026-10-15')
  const rows = db.prepare('SELECT * FROM todos WHERE recur_parent = ? ORDER BY due_at').all(rule.id)
  core.setTodoDone(rows[0].id, true, me.id)
  core.setTodoDone(rows[0].id, true, friend.id)
  core.setTodoDone(rows[1].id, true, friend.id)
  core.toggleReaction(rows[1].id, me.id, '🌟')
  const finished = core.getTodo(rows[0].id)
  const partial = core.getTodo(rows[1].id)
  const receipt = core.deleteTodo(rule.id)
  assert.equal(core.getTodo(rule.id), undefined)
  assert.equal(core.getTodo(rows[2].id), undefined)
  assert.equal(core.getTodo(rows[0].id).recur_parent, null)
  assert.equal(core.getTodo(rows[1].id).done_by, partial.done_by)
  assert.equal(core.listTrash()[0].item_count, 2, 'rule and uncompleted child are recoverable; retained history stays live')
  core.updateTodo(rows[1].id, { title: 'Edited retained partial history' })
  core.restoreTrash(receipt)
  assert.equal(core.getTodo(rows[0].id).completed_at, finished.completed_at)
  assert.equal(core.getTodo(rows[0].id).recur_parent, rule.id)
  assert.equal(core.getTodo(rows[1].id).title, 'Edited retained partial history')
  assert.equal(core.getTodo(rows[1].id).recur_parent, null, 'edited history stays independent')
  assert.equal(core.getTodo(rows[1].id).done_by, partial.done_by)
  assert.equal(core.listReactionsForTodo(rows[1].id)[0].emoji, '🌟')
  assert.equal(core.getTodo(rows[2].id).recur_parent, rule.id)
})

test('a changed repeat rule keeps its new schedule while restoring the old occurrence independently', () => {
  const rule = event('Class', { recurrence: JSON.stringify({ freq: 'weekly', days: [4], startDate: '2026-10-08', endDate: '2026-10-22' }) })
  const dated = core.listEvents({ from: iso('2026-10-08', '00:00'), to: iso('2026-10-09', '00:00') })[0]
  const receipt = core.deleteEvent(dated.id)
  const modified = JSON.stringify({ freq: 'weekly', days: [5], startDate: '2026-10-09', endDate: '2026-10-23', excludedDates: ['2026-10-08'] })
  db.prepare('UPDATE events SET recurrence = ? WHERE id = ?').run(modified, rule.id)
  core.restoreTrash(receipt)
  assert.equal(core.getEvent(dated.id).recur_parent, null)
  assert.equal(core.getEvent(rule.id).recurrence, modified)
})

test('remote occurrence undo cancels its tombstone and retains a dirty remote identity only with a cached series', () => {
  const row = event('Remote class', { caldav_uid: 'calendar-series', caldav_recurrence_id: '2026-10-08T09:00:00', source: 'caldav', caldav_url: 'https://calendar.example/class.ics' })
  const ics = ['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','UID:calendar-series','DTSTART:20261008T090000','DTEND:20261008T100000','RRULE:FREQ=WEEKLY;COUNT=3','SUMMARY:Remote class','END:VEVENT','END:VCALENDAR'].join('\r\n')
  db.prepare('INSERT INTO calendar_resources(person_id,uid,ics) VALUES (?,?,?)').run(me.id, row.caldav_uid, ics)
  const receipt = core.deleteEvent(row.id)
  db.prepare('INSERT INTO calendar_resource_changes(id,person_id,uid,patch) VALUES (?,?,?,?)').run('deleted-own',me.id,row.caldav_uid,JSON.stringify({scope:'exclude',uid:row.caldav_uid,recurrenceId:row.caldav_recurrence_id}))
  db.prepare('INSERT INTO calendar_resource_changes(id,person_id,uid,patch) VALUES (?,?,?,?)').run('deleted-other',me.id,row.caldav_uid,JSON.stringify({scope:'exclude',uid:row.caldav_uid,recurrenceId:'2026-10-15T09:00:00'}))
  assert.equal(db.prepare('SELECT COUNT(*) n FROM calendar_tombstones').get().n, 1)
  core.restoreTrash(receipt)
  assert.equal(core.getEvent(row.id).caldav_uid, row.caldav_uid)
  assert.equal(core.getEvent(row.id).calendar_dirty, 1)
  assert.equal(core.getEvent(row.id).calendar_restore, 1)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM calendar_tombstones').get().n, 0)
  assert.equal(db.prepare('SELECT 1 FROM calendar_resource_changes WHERE id = ?').get('deleted-own'),undefined)
  assert.ok(db.prepare('SELECT 1 FROM calendar_resource_changes WHERE id = ?').get('deleted-other'))
  const detached = core.deleteEvent(row.id)
  db.prepare('DELETE FROM calendar_resources').run()
  core.restoreTrash(detached)
  assert.equal(core.getEvent(row.id).caldav_uid, null)
  assert.equal(core.getEvent(row.id).caldav_recurrence_id, null)
  assert.equal(core.getEvent(row.id).source, 'local')
  assert.equal(core.getEvent(row.id).calendar_restore, 0)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM calendar_tombstones').get().n, 1,'missing series keeps original remote deletion')
})

test('Trash restore detaches an occurrence when the cached remote series changed its clock', () => {
  const row = event('Old remote date', { caldav_uid: 'changed-clock', caldav_recurrence_id: '2026-10-08T09:00:00', source: 'caldav' })
  const receipt = core.deleteEvent(row.id)
  const changed = ['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','UID:changed-clock','DTSTART:20261008T110000','DTEND:20261008T120000','RRULE:FREQ=WEEKLY;COUNT=3','SUMMARY:Changed series','END:VEVENT','END:VCALENDAR'].join('\r\n')
  db.prepare('INSERT INTO calendar_resources(person_id,uid,ics) VALUES (?,?,?)').run(me.id,row.caldav_uid,changed)
  core.restoreTrash(receipt)
  const restored = core.getEvent(row.id)
  assert.equal(restored.starts_at,row.starts_at)
  assert.equal(restored.caldav_uid,null)
  assert.equal(restored.calendar_restore,0)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM calendar_tombstones').get().n,1)
})

test('Trash retains deletions for 30 days, and profile/cascade maintenance never leaves orphan entries', () => {
  const removed = core.deleteTodo(task('Old deletion').id)
  db.prepare('UPDATE trash_items SET deleted_at = ? WHERE id = ?').run('2000-01-01T00:00:00.000Z', removed)
  assert.equal(core.purgeTrash(), 1)
  const extra = core.createPerson({ name: 'Temporary profile' })
  const profileTask = core.createTodo({ title: 'Profile-owned', person_id: extra.id })
  core.deleteTodo(profileTask.id)
  db.prepare('INSERT INTO recurrence_exclusions(kind,parent_id,day,excluded) VALUES (?,?,?,?)').run('task',profileTask.id,'2026-10-10',1)
  core.deletePerson(extra.id)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM trash_items WHERE person_id = ?').get(extra.id).n, 0)
  assert.equal(db.prepare('SELECT 1 FROM recurrence_exclusions WHERE parent_id = ?').get(profileTask.id),undefined)
  const goal = core.createGoal({ title: 'Removed goal', person_id: me.id })
  task('Cascade removed', { goal_id: goal.id })
  core.deleteGoal(goal.id)
  assert.equal(core.listTrash().length, 0)
})

test('backup is durable and restore is atomic, creates a safety copy, and keeps sync identity/calendar connections', () => {
  sync.installSyncJournal(db)
  const device = db.prepare('SELECT value FROM __sync_meta WHERE key = ?').get('device').value
  const row = task('Backed up task')
  core.setDailyNote('2026-10-10', 'Unicode café 🌙\nFinal line', me.id)
  db.prepare('INSERT INTO settings(key,value) VALUES (?,?)').run(`caldav:${me.id}`, 'current-private-connection')
  const remote = event('Backed up remote', { caldav_uid: 'remote-calendar-event', source: 'caldav' })
  const copy = core.createBackup()
  const parsed = JSON.parse(fs.readFileSync(backupFile(copy.id), 'utf8'))
  assert.equal(parsed.format, 'doneline-backup')
  assert.ok(!Object.keys(parsed.tables).some(name => name.startsWith('__sync_')))
  assert.equal(parsed.tables.calendar_tombstones, undefined)
  assert.equal(parsed.tables.calendar_resources, undefined)
  assert.equal(parsed.tables.calendar_resource_changes, undefined)
  assert.ok(!JSON.stringify(parsed).includes('current-private-connection'))
  core.updateTodo(row.id, { title: 'Newer current task' })
  const queued = db.prepare('SELECT operation_id FROM __sync_outbox ORDER BY seq DESC LIMIT 1').get().operation_id
  core.setDailyNote('2026-10-10', 'Current draft before restore', me.id)
  db.prepare('INSERT INTO calendar_tombstones(person_id,uid) VALUES (?,?)').run(me.id, 'historic-delete')
  const restored = core.restoreBackup(copy.id)
  assert.equal(core.getTodo(row.id).title, 'Backed up task')
  assert.equal(core.getDailyNote('2026-10-10', me.id).body, 'Unicode café 🌙\nFinal line')
  assert.equal(db.prepare('SELECT value FROM settings WHERE key = ?').get(`caldav:${me.id}`).value, 'current-private-connection')
  assert.equal(db.prepare('SELECT COUNT(*) n FROM calendar_tombstones').get().n, 0)
  assert.equal(core.getEvent(remote.id).calendar_restore, 1)
  assert.equal(core.getEvent(remote.id).calendar_dirty, 1)
  assert.equal(db.prepare('SELECT value FROM __sync_meta WHERE key = ?').get('device').value,device)
  assert.ok(db.prepare('SELECT 1 FROM __sync_outbox WHERE operation_id = ?').get(queued),'existing unacknowledged local changes remain queued')
  assert.ok(db.prepare("SELECT 1 FROM __sync_outbox WHERE table_name = 'todos' AND row_json LIKE ?").get('%Backed up task%'),'restore queues restored rows using normal sync triggers')
  assert.equal(restored.safetyBackup.reason, 'before-restore')
  const safety = JSON.parse(fs.readFileSync(backupFile(restored.safetyBackup.id), 'utf8'))
  const titles = safety.tables.todos.rows.map(row => row[safety.tables.todos.columns.indexOf('title')])
  assert.ok(titles.includes('Newer current task'))
  assert.throws(() => core.restoreBackup('../private.db'), /existing Doneline backup/)
  const child = require('node:child_process').spawnSync(process.execPath, ['-e', `const c=require(${JSON.stringify(compiled)}); c.restoreBackup(${JSON.stringify(copy.id)}); console.log(JSON.stringify(c.getTodo(${JSON.stringify(row.id)}))); c.closeDb()`],
    { env: process.env, encoding: 'utf8', windowsHide: true, timeout: 10000 })
  assert.equal(child.status, 0, child.stderr || child.error?.message)
  assert.equal(JSON.parse(child.stdout.trim().split(/\r?\n/).at(-1)).title, 'Backed up task', 'Backup restores into a fresh process without the original database')

  const corrupted = JSON.parse(fs.readFileSync(backupFile(copy.id), 'utf8'))
  const goal = core.createGoal({ title: 'Existing goal', person_id: me.id })
  const taskColumns = corrupted.tables.todos.columns
  corrupted.tables.todos.rows[0][taskColumns.indexOf('goal_id')] = 'missing-goal'
  fs.writeFileSync(backupFile(copy.id), JSON.stringify(corrupted))
  assert.throws(() => core.restoreBackup(copy.id), /FOREIGN KEY/)
  assert.ok(core.getGoal(goal.id), 'Failed restore rolled back every deleted table')
  assert.equal(core.getTodo(row.id).title, 'Backed up task')
  const forbidden = structuredClone(parsed)
  const keys = forbidden.tables.settings.columns
  forbidden.tables.settings.rows.push(keys.map(key=>key==='key'?`caldav:${friend.id}`:'historic-secret'))
  fs.writeFileSync(backupFile(copy.id), JSON.stringify(forbidden))
  assert.throws(() => core.restoreBackup(copy.id), /Calendar connections are managed separately/)
  assert.equal(db.prepare('SELECT value FROM settings WHERE key = ?').get(`caldav:${me.id}`).value, 'current-private-connection')
  assert.equal(db.prepare('SELECT value FROM settings WHERE key = ?').get(`caldav:${friend.id}`),undefined)
})

test('backup lists and daily snapshots are isolated to the active workspace database', () => {
  const localCopies = core.listBackups().map(copy=>copy.id)
  const child = require('node:child_process').spawnSync(process.execPath, ['-e', `const c=require(${JSON.stringify(compiled)}); const before=c.listBackups();c.getDb();const copy=c.ensureDailyBackup();console.log(JSON.stringify({before,copy,after:c.listBackups()}));c.closeDb();`],
    { env: { ...process.env,DONELINE_DB:path.join(directory,'other-private-workspace.db') },encoding:'utf8',windowsHide:true,timeout:10000 })
  assert.equal(child.status,0,child.stderr || child.error?.message)
  const result = JSON.parse(child.stdout.trim().split(/\r?\n/).at(-1))
  assert.deepEqual(result.before,[],'another database never offers backups from this workspace')
  assert.equal(result.after.length,1,'another workspace creates its own daily backup')
  assert.ok(!localCopies.includes(result.copy.id))
  assert.deepEqual(core.listBackups().map(copy=>copy.id),localCopies,'other workspace backup stays out of current list')
})

test('automatic backups are one per local day and older daily copies expire while manual copies stay', () => {
  const old = core.ensureDailyBackup(new Date('2026-01-01T12:00:00'))
  const manual = core.createBackup('manual', new Date('2026-01-01T13:00:00'))
  const current = core.ensureDailyBackup(new Date('2026-03-01T12:00:00'))
  const same = core.ensureDailyBackup(new Date('2026-03-01T22:00:00'))
  assert.equal(current.id, same.id)
  const copies = core.listBackups()
  assert.equal(copies.some(copy => copy.id === old.id), false)
  assert.equal(copies.some(copy => copy.id === manual.id), true)
})
